# Generated by Django 5.2.17 on 2026-09-17 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("resume_link", models.URLField()),
                ("repository_link", models.URLField()),
                ("action_run_link", models.URLField()),
                ("submitted_at", models.DateTimeField(db_index=True)),
                ("receipt", models.CharField(max_length=100, unique=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("phone_screen_scheduled", "Phone screen scheduled"),
                            ("interview_scheduled", "Interview scheduled"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=32,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StageEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("phone_screen_scheduled", "Phone screen scheduled"),
                            ("interview_scheduled", "Interview scheduled"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=32,
                    ),
                ),
                ("entered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_entries",
                        to="apply.application",
                    ),
                ),
            ],
            options={
                "ordering": ["entered_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stage_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="apply.stageentry",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
    ]
