# Generated by Django 5.2.17 on 2026-09-17 15:40

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    """Indexes shaped like the list endpoint's queries.

    The unfiltered list sorts by (submitted_at DESC, id DESC), so the single
    column index on submitted_at becomes a composite one that covers the whole
    sort. The email filter is case-insensitive, which Postgres runs as
    UPPER(email) = UPPER(%s), so the plain email index becomes one on
    UPPER(email).
    """

    dependencies = [
        ("apply", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="application",
            name="submitted_at",
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["-submitted_at", "-id"], name="apply_app_newest_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                django.db.models.functions.text.Upper("email"),
                name="apply_app_email_upper_idx",
            ),
        ),
    ]
