# Generated by Django 5.2.17 on 2026-09-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="stage",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("phone_screen_scheduled", "Phone screen scheduled"),
                    ("interview_scheduled", "Interview scheduled"),
                    ("hired", "Hired"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="new",
                max_length=32,
            ),
        ),
    ]
