# Generated by Django 5.2.17 on 2026-09-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apply", "0002_application_stage_index"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stageentry",
            options={"ordering": ["id"]},
        ),
    ]
