"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"


def secret(name, dev_default):
    """A secret from the environment. The dev default only applies with DEBUG on.

    With DEBUG off and the variable unset, refuse to start: a forgotten
    DJANGO_SECRET_KEY would make every session forgeable, and a forgotten
    APPLICANT_SIGNING_SECRET would let anyone submit an application.
    """
    value = os.environ.get(name)
    if value:
        return value
    if DEBUG:
        return dev_default
    raise ImproperlyConfigured(f"{name} must be set when DJANGO_DEBUG=0.")


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secret("DJANGO_SECRET_KEY", "django-insecure-dev-only-key")

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "apply",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


def database_from_url(url):
    """Turn a postgres://user:pass@host/db?sslmode=require URL into a Django setting.

    Vercel has no disk, so there the data lives in Neon Postgres and
    DATABASE_URL points at it. Small enough to not need dj-database-url.
    """
    from urllib.parse import parse_qs, urlparse

    parts = urlparse(url)
    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": parts.path.lstrip("/"),
        "USER": parts.username,
        "PASSWORD": parts.password,
        "HOST": parts.hostname,
        "PORT": parts.port or 5432,
        "OPTIONS": {k: v[0] for k, v in parse_qs(parts.query).items()},
    }


if os.environ.get("DATABASE_URL"):
    DATABASES = {"default": database_from_url(os.environ["DATABASE_URL"])}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.environ.get("DATABASE_PATH", BASE_DIR / "db.sqlite3"),
            # SQLite ignores select_for_update(). With the default deferred
            # transaction two gunicorn workers can both read the old stage and
            # the second write fails with "database is locked". IMMEDIATE takes
            # the write lock when atomic() opens, so the second waits instead.
            "OPTIONS": {"transaction_mode": "IMMEDIATE"},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

# The built React app. WhiteNoise serves its files at the site root
# (/assets/*.js, /favicon.svg) and config.spa serves index.html for routes.
FRONTEND_DIST = BASE_DIR / "frontend" / "dist"
WHITENOISE_ROOT = FRONTEND_DIST

# On Vercel nothing runs collectstatic, so WhiteNoise finds the admin's files
# in site-packages instead of STATIC_ROOT. The frontend is served by Vercel's
# static layer there, not by Django.
WHITENOISE_USE_FINDERS = os.environ.get("VERCEL") == "1"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# HMAC secret shared with the GitHub Action that POSTs submissions.
APPLICANT_SIGNING_SECRET = secret("APPLICANT_SIGNING_SECRET", "dev-only-secret")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# The React dev server proxies /api to Django. With changeOrigin, Django sees
# Host localhost:8000 but Origin localhost:5173, so POSTs need this to pass CSRF.
# In production the deployed origin comes from the environment.
CSRF_TRUSTED_ORIGINS = ["http://localhost:5173"] + [
    origin for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if origin
]

if not DEBUG:
    # Vercel terminates TLS and forwards the scheme in this header.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Vercel only serves HTTPS. A short max-age keeps a mistake recoverable.
    SECURE_HSTS_SECONDS = 3600
